### ISSUE TITLE
Problema con la lectura del puerto serie

### ISSUE THREAD

**Issue by Adriang2211** [aigora/twE105_1920-vitamina_c#3]
La función de lectura del puerto serie (Serial_read) añadida en el commit 7f55f6ff83e99f79832cd7483c4d7a0d3ae3480b (en la rama "Serial") no funciona.

**Comment by oscarperpinan** [comment]
Lo revisaré.

**Comment by oscarperpinan** [comment]
Veo que estáis usando la librería Windows.h. Esto hace que el código no sea portable, es decir, no se puede compilar/ejecutar en diferentes sistemas operativos. En particular, no se puede compilar en Linux, que es con lo que yo trabajo. Además, no conozco ni los tipos de datos ni las funciones de esta librería, de forma que no puedo ayudaros a encontrar el problema con el código de este commit.

En este sentido, os recomiendo que, en la medida de lo posible, modifiquéis el código para usar funciones de las librerías estándar y dejar de usar esta librería. Soy consciente de que queda poco tiempo para la entrega, y es posible que este cambio no sea viable a estas alturas. Si así fuese, no os preocupéis. La complejidad añadida de trabajar con Arduino compensa sobradamente esta pega. Pero, por favor, documentad con detalle el uso de todas las funciones y tipos de datos que sean específicos de esta librería.

**Comment by Adriang2211** [comment]
Hemos optado por las siguientes soluciones (más o menos parciales debido, efectivamente, a la falta de tiempo):
 - Para que el programa pueda ejecutarse en sistemas operativos que no sean Windows, hemos creado una versión del proyecto que no utiliza el puerto serie y por lo tanto no utiliza la librería Windows.h (Ya está en el repositorio dicha versión a falta de pequeñas modificaciones estéticas).
 - Continuamos trabajando en una versión que esperamos tener a tiempo que utilizará la librería Windows.h para funciones de envío de datos por el puerto serie. Para no tener que utilizar la lectura del puerto serie, hay un nuevo programa de Arduino que guarda los mensajes que recibe en una tarjeta microSD en lugar de enviarlos al ordenador.

**Comment by oscarperpinan** [comment]
Perfecto. Gracias por el esfuerzo adicional.

**Comment by Adriang2211** [comment]
Añado un último comentario aclaratorio a esta issue:
Han surgido problemas adicionales con el puerto serie. Hemos detectado que solo se envía uno de los bloques de texto que deberían enviarse (el primero, que sí que funciona completamente, llegando a enviarse por radio y recibirse) y no conseguimos encontrar el error. Sabemos que lo más probable eso sí, es que se encuentre en la función de envío de Serial.h, porque las cadenas de texto que lee el menú principal, llegan sin problemas hasta esa función pero parecen no enviarse.

**Comment by oscarperpinan** [comment]
De acuerdo. 
En cualquier caso, el proyecto que habéis realizado es muy bueno, y excede los objetivos que se plantean en la asignatura. Enhorabuena.
