### ISSUE TITLE
Entrega final del código

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-vitamina_c#4]
El día 22 de mayo es la fecha de entrega del trabajo. Al finalizar ese día, el código del trabajo debe estar completo, sin errores de compilación, y con las funcionalidades descritas en el README y en el diagrama de flujo. 

Recordad que:

- Es obligatorio que el trabajo se realice con **funciones**. 
- Es obligatorio utilizar **vectores de estructuras**. 
- Es obligatorio utilizar **ficheros**.
- Está prohibido el uso de variables globales.

**Debéis cerrar esta issue cuando deis por finalizado el trabajo**.

**Comment by PedroLeon00** [comment]
Presentamos dos proyectos el primero es solo compatible con windows pero tiene el envío de datos vía arduino, el segundo es compatible con cualquier sistema operativo. (Ver wiki)

**Comment by PedroLeon00** [comment]
Proyecto entregado con los problemas comentados en la issue del puerto serie
