### ISSUE TITLE
Entrega final: documentación en wiki

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-vitamina_c#5]
Acompañando al código, hay que elaborar la documentación del proyecto. Esta documentación debe estar recogida en la wiki del repositorio. 

En el punto de inicio tenéis las [instrucciones](https://github.com/aigora/punto_inicio/wiki/6.-C%C3%B3mo-presentar-el-trabajo) necesarias.  

**Debéis cerrar esta issue cuando deis por finalizado el trabajo**.

**Comment by PedroLeon00** [comment]
Wiki lista

**Comment by Adriang2211** [comment]
Todavía hay unos cambios menores pendientes y existe la posibilidad de que haya que añadir alguna cosa a la wiki.

**Comment by PedroLeon00** [comment]
Añadidas nuevas limitaciones
