### ISSUE TITLE
Error de ejecución en en Vitamina_C_Simple

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-vitamina_c#7]
La versión "simple" del programa tiene un error de ejecución (`segmentation fault`) nada más comenzar. Por favor, revisad el código y haced los cambios necesarios para que funcione correctamente.

**Comment by PedroLeon00** [comment]
Hemos ejecutado el programa satisfactoriamente, al buscar información sobre el error hemos visto que puede ser problema del compilador empleado o que se esté usando un sistema unix con memoria virtual y el programa pida emplear memoria que no esté en la lista de memoria con permisos asociados.
Contacte con nosotros si el problema continua, para darle una posible solución.

**Comment by oscarperpinan** [comment]
Lo probaré de nuevo en una máquina con Windows.

Disculpa que no te haya podido atender en Teams. Estaba en una revisión de examen.

**Comment by PedroLeon00** [comment]
Sin problema, nos interesa este bug. Seguimos en contacto por las Issues.

**Comment by oscarperpinan** [comment]
Ya he podido comprobar el programa en una máquina con Windows y funciona sin problemas. He comprobado nuevamente a compilar en Unix y la ejecución se para con un _segmentation fault_.
Cierro la issue.
